# Generated by Django 4.2.16 on 2024-12-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPro',
        ),
    ]
