# Generated by Django 4.2.16 on 2024-11-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Bank', 'Bank')], default='Manual', max_length=10),
        ),
    ]
