# Generated by Django 4.2.16 on 2024-12-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_track', '0004_banktransaction_linkedaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='LinkedAccount',
        ),
    ]
