# Generated by Django 4.2.16 on 2024-12-19 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin_track', '0007_alter_transaction_user_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('rent', 'Rent'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
