# Generated by Django 4.2.16 on 2024-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_track', '0008_transaction_category_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='actual',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
