# Generated by Django 4.2.16 on 2024-12-19 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fin_track', '0009_rename_amount_budget_actual_remove_budget_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='actual',
            new_name='budgeted_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
