# Generated by Django 4.2.16 on 2024-12-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_track', '0011_income_budgetcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='budgeted_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
        migrations.AddField(
            model_name='budget',
            name='actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='BudgetCategory',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
