# Generated by Django 4.2.16 on 2025-01-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_track', '0014_alter_budget_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
