# Generated by Django 4.2.16 on 2025-01-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_track', '0016_remove_budget_total_income_totalincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalincome',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
    ]
