# Generated by Django 4.2.16 on 2025-01-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin_track', '0017_alter_totalincome_total_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
